#!/bin/bash

echo "CG> redirect-streams -i \"err\" \"compilation\""

java -Dcodingame.compiler.output=/project/results/compilation.json -jar /usr/src/codingame/java-compiler/java-compiler.jar "$@"

echo "CG> redirect-streams -r -i \"err\" \"compilation\""